### ISSUE TITLE
How to close a popup not only with C-g?

### ISSUE THREAD

**Issue by timmli** [xuchunyang/flyspell-popup#4]
It seems that I can only close a popup with `C-g` when I don't want to choose a correction. Yet I would like to be able to close a popup with `<left>`, `<right>`, ... as well. Ideally, `flyspell-popup` would close a popup upon pressing any key **except** the defined ones such as `<up>`, `<down>`, `<enter>` and `<tab>`. 

Thanks!

**Comment by xuchunyang** [comment]
I just pushed a commit for this, keys which don't have special meaning for a popup, i.e., not defined by `popup-menu-keymap`, will close the popup.

**Comment by timmli** [comment]
Good! Works better for me now. I'll close the issue. 

One minor related question: Do you know how one can bind `<tab>` to execute a selected correction (similarly to `<return>`)?

**Comment by xuchunyang** [comment]
```el
(with-eval-after-load "popup"
  (define-key popup-menu-keymap (kbd "TAB") 'popup-select))
```

**Comment by timmli** [comment]
Thanks!
